import Logo from "@/app/_components/Logo";
import Navigation from "@/app/_components/Navigation";
import "@/app/_styles/globals.css";
import { Josefin_Sans } from "next/font/google";

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
  // weight: ["400", "700"],
  // variable: "--font-family-sans-serif",
});

interface RootLayoutProps {
  children: React.ReactNode;
}
export const metadata = {
  // title: "The wild Oasis",
  // description: "Generated by The wild Oasis",
  title: {
    template: "%s The wild Oasis",
    default: "welcome The wild Oasis",
    description:
      "Luxurious cabin hotel located in the heart of Italian Dolomites, surrounded by beautiful mountains and dark forests",
  },
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} bg-primary-950 text-primary-50 min-h-screen`}
      >
        <header>
          <Logo />
        </header>
        <Navigation />
        <main>{children}</main>
        <footer>Copyright by the wild oasis</footer>
      </body>
    </html>
  );
}
